#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";RUN_DIR="$(mktemp -d "${TMPDIR:-/tmp}/auraedu-admissions-smoke.XXXXXX")";GO_BIN="${GO_BIN:-/opt/homebrew/bin/go}";COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-auraedu-infra}";PORT="${ADMISSIONS_PORT:-18114}";CRM_PORT="${CRM_PORT:-18105}";ANALYTICS_PORT="${ANALYTICS_PORT:-18102}";FILE_PORT="${FILE_OWNERSHIP_PORT:-18193}";INTERNAL_TOKEN="${INTERNAL_SERVICE_TOKEN:-admissions-smoke-token}";TENANT="${TENANT_ID:-upshs}";PIDS=()
cleanup() { for pid in "${PIDS[@]:-}"; do kill "$pid" 2>/dev/null || true; done; wait "${PIDS[@]:-}" 2>/dev/null || true; }
trap cleanup EXIT INT TERM
fail() { printf 'Admissions conversion smoke failed: %s\n' "$1" >&2; for log in "$RUN_DIR"/*.log; do [[ -f "$log" ]] && tail -n 100 "$log" >&2; done; exit 1; }
notification_count() { COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d notification -tAc "$1" | tr -d '[:space:]'; }
command -v docker >/dev/null||fail "docker required";command -v curl >/dev/null||fail "curl required";command -v jq >/dev/null||fail "jq required";[[ -x "$GO_BIN" ]]||fail "Go missing"
cd "$ROOT_DIR";COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml up -d postgres nats >/dev/null
COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d postgres -v ON_ERROR_STOP=1 <<'SQL' >/dev/null
SELECT 'CREATE DATABASE admissions' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='admissions')\gexec
SELECT 'CREATE DATABASE crm' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='crm')\gexec
SELECT 'CREATE DATABASE notification' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='notification')\gexec
SELECT 'CREATE DATABASE analytics' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='analytics')\gexec
SQL
FILE="$(uuidgen|tr '[:upper:]' '[:lower:]')";PORT="$FILE_PORT" INTERNAL_SERVICE_TOKEN="$INTERNAL_TOKEN" SMOKE_FILE_ID="$FILE" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./tools/smoke/helpers/file-ownership-server.go >"$RUN_DIR/file-ownership.log" 2>&1 &PIDS+=("$!")
attempts=60;until curl --fail --silent "http://127.0.0.1:$FILE_PORT/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "file ownership verifier not ready";sleep 1;done
(cd "$ROOT_DIR/apps/crm-service" && FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/crm?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" INTERNAL_SERVICE_TOKEN="$INTERNAL_TOKEN" PORT="$CRM_PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/crm-service server) >"$RUN_DIR/crm-server.log" 2>&1 &PIDS+=("$!")
attempts=60;until curl --fail --silent "http://127.0.0.1:$CRM_PORT/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "CRM not ready";sleep 1;done
DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/crm?sslmode=disable" MIGRATIONS_PATH="$ROOT_DIR/apps/crm-service/migrations" NATS_URL="nats://127.0.0.1:4222" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./apps/crm-service/cmd/crm-service worker >"$RUN_DIR/crm-worker.log" 2>&1 &PIDS+=("$!")
(cd "$ROOT_DIR/apps/analytics-service" && FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/analytics?sslmode=disable" PORT="$ANALYTICS_PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/analytics-service server) >"$RUN_DIR/analytics-server.log" 2>&1 &PIDS+=("$!")
attempts=60;until curl --fail --silent "http://127.0.0.1:$ANALYTICS_PORT/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "analytics service not ready";sleep 1;done
(cd "$ROOT_DIR/apps/analytics-service" && DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/analytics?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/analytics-service worker) >"$RUN_DIR/analytics-worker.log" 2>&1 &PIDS+=("$!")
(cd "$ROOT_DIR/apps/notification-service" && FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/notification?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" SERVICE_CRM_URL="http://127.0.0.1:$CRM_PORT" INTERNAL_SERVICE_TOKEN="$INTERNAL_TOKEN" NOTIFICATION_PROVIDER=mock GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/notification-service worker) >"$RUN_DIR/notification-worker.log" 2>&1 &PIDS+=("$!")
sleep 3
FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/admissions?sslmode=disable" MIGRATIONS_PATH="$ROOT_DIR/apps/admissions-service/migrations" NATS_URL="nats://127.0.0.1:4222" SERVICE_FILE_URL="http://127.0.0.1:$FILE_PORT" INTERNAL_SERVICE_TOKEN="$INTERNAL_TOKEN" PORT="$PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./apps/admissions-service/cmd/admissions-service server >"$RUN_DIR/server.log" 2>&1 &PIDS+=("$!")
attempts=60;until curl --fail --silent "http://127.0.0.1:$PORT/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "service not ready";sleep 1;done
DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/admissions?sslmode=disable" MIGRATIONS_PATH="$ROOT_DIR/apps/admissions-service/migrations" NATS_URL="nats://127.0.0.1:4222" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./apps/admissions-service/cmd/admissions-service worker >"$RUN_DIR/worker.log" 2>&1 &PIDS+=("$!")
H=(-H 'Content-Type: application/json' -H "X-Actor-Tenant: $TENANT")
NONCE="$(date +%s)-$$";CODE="SMK$(date +%s)";SLUG="smoke-programme-$NONCE"
STARTS="$(date -u -v+30d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '30 days' +%Y-%m-%dT%H:%M:%SZ)";CLOSES="$(date -u -v+14d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '14 days' +%Y-%m-%dT%H:%M:%SZ)";OPENS="$(date -u -v-1H +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '1 hour ago' +%Y-%m-%dT%H:%M:%SZ)"
CATALOGUE_HEADERS=(-H 'X-Actor-User: admissions-manager' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: admissions.catalogue.manage,admissions.application.read')
PROGRAMME_RESPONSE="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/programmes" "${H[@]}" "${CATALOGUE_HEADERS[@]}" --data "{\"code\":\"$CODE\",\"name\":\"Applied Science $NONCE\",\"slug\":\"$SLUG\",\"summary\":\"Verified smoke programme\",\"description\":\"A published programme used to prove catalogue-to-application conversion.\"}")";PROGRAMME="$(jq -r .id<<<"$PROGRAMME_RESPONSE")";[[ -n "$PROGRAMME"&&"$PROGRAMME" != null ]]||fail "programme creation failed"
INTAKE_RESPONSE="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/programmes/$PROGRAMME/intakes" "${H[@]}" "${CATALOGUE_HEADERS[@]}" --data "{\"name\":\"September $NONCE\",\"starts_at\":\"$STARTS\",\"application_opens_at\":\"$OPENS\",\"application_closes_at\":\"$CLOSES\",\"capacity\":120}")";INTAKE="$(jq -r .id<<<"$INTAKE_RESPONSE")";[[ -n "$INTAKE"&&"$INTAKE" != null ]]||fail "intake creation failed"
DRAFT_START="$(curl -sS -o /dev/null -w '%{http_code}' -X POST "http://127.0.0.1:$PORT/api/v1/applications" "${H[@]}" -H 'X-Actor-User: draft-applicant' -H 'X-Actor-Role: applicant' -H 'X-Actor-Permissions: admissions.application.create' --data "{\"programme_id\":\"$PROGRAMME\",\"intake_id\":\"$INTAKE\"}")";[[ "$DRAFT_START" == 404 ]]||fail "draft catalogue application returned $DRAFT_START"
curl --fail-with-body -sS -X PATCH "http://127.0.0.1:$PORT/api/v1/programmes/$PROGRAMME" "${H[@]}" "${CATALOGUE_HEADERS[@]}" --data '{"status":"published"}' >/dev/null
curl --fail-with-body -sS -X PATCH "http://127.0.0.1:$PORT/api/v1/intakes/$INTAKE" "${H[@]}" "${CATALOGUE_HEADERS[@]}" --data '{"status":"open"}' >/dev/null
PUBLIC_CATALOGUE="$(curl --fail-with-body -sS "http://127.0.0.1:$PORT/api/v1/public/programmes" -H "X-Tenant-Code: $TENANT")";jq -e --arg programme "$PROGRAMME" --arg intake "$INTAKE" 'any(.data[]; .id==$programme and any(.intakes[]; .id==$intake))'<<<"$PUBLIC_CATALOGUE" >/dev/null||fail "published catalogue not publicly discoverable"
OTHER_CATALOGUE_STATUS="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/api/v1/public/programmes" -H 'X-Tenant-Code: school-two')";[[ "$OTHER_CATALOGUE_STATUS" == 403 ]]||fail "disabled-tenant catalogue returned $OTHER_CATALOGUE_STATUS"
LEAD="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$CRM_PORT/api/v1/public/leads" -H 'Content-Type: application/json' -H "X-Tenant-Code: $TENANT" -H "Idempotency-Key: admissions-smoke-$(date +%s)-$$" --data '{"first_name":"Ama","last_name":"Mensah","email":"ama.admissions.smoke@example.com","phone":null,"preferred_programme_ids":[],"source":"admissions_smoke","consent":{"privacy_notice_version":"2026-07-18","email":true,"sms":false,"whatsapp":false,"voice":false}}')";LEAD_ID="$(jq -r .lead_id<<<"$LEAD")";[[ -n "$LEAD_ID"&&"$LEAD_ID" != null ]]||fail "lead capture failed"
CREATED="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Role: applicant' -H 'X-Actor-Permissions: admissions.application.create,admissions.application.update,admissions.application.submit,admissions.offer.accept' --data "{\"lead_id\":\"$LEAD_ID\",\"programme_id\":\"$PROGRAMME\",\"intake_id\":\"$INTAKE\"}")";ID="$(jq -r .id<<<"$CREATED")";[[ -n "$ID"&&"$ID" != null ]]||fail "start failed"
curl --fail-with-body -sS -X PATCH "http://127.0.0.1:$PORT/api/v1/applications/$ID" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Role: applicant' -H 'X-Actor-Permissions: admissions.application.update' --data '{"legal_name":"Ama Mensah","email":"ama@example.com","phone":"+233240000000"}' >/dev/null
INCOMPLETE="$(curl -sS -o /dev/null -w '%{http_code}' -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/submit" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Permissions: admissions.application.submit' --data '{}')";[[ "$INCOMPLETE" == 422 ]]||fail "incomplete checklist returned $INCOMPLETE"
curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/documents" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Permissions: admissions.application.update' --data "{\"file_id\":\"$FILE\",\"document_type\":\"transcript\",\"file_name\":\"results.pdf\"}" >/dev/null
curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/submit" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Permissions: admissions.application.submit' --data '{}' >/dev/null
AI="$(curl -sS -o /dev/null -w '%{http_code}' -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/review" "${H[@]}" -H 'X-Actor-User: ai-1' -H 'X-Actor-Role: ai_service_account' -H 'X-Actor-Permissions: admissions.application.review' --data '{"decision":"admitted","note":"automatic"}')";[[ "$AI" == 403 ]]||fail "AI decision returned $AI"
curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/review" "${H[@]}" -H 'X-Actor-User: reviewer' -H 'X-Actor-Role: admissions_officer' -H 'X-Actor-Permissions: admissions.application.review' --data '{"decision":"admitted","note":"Qualifications and evidence verified manually"}' >/dev/null
EXPIRES="$(date -u -v+7d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '7 days' +%Y-%m-%dT%H:%M:%SZ)";curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/offer" "${H[@]}" -H 'X-Actor-User: registrar' -H 'X-Actor-Role: registrar' -H 'X-Actor-Permissions: admissions.offer.issue' --data "{\"conditions\":\"Bring original certificates at enrolment\",\"expires_at\":\"$EXPIRES\"}" >/dev/null
attempts=30;until [[ "$(notification_count "SELECT count(*) FROM messages WHERE metadata->>'application_id'='$ID' AND status='sent'")" == "1" && "$(notification_count "SELECT count(*) FROM messages WHERE metadata->>'application_id'='$ID' AND status='pending' AND scheduled_at IS NOT NULL")" == "1" ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "offer notice and reminder were not created";sleep 1;done
ACCEPTED="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/applications/$ID/offer/accept" "${H[@]}" -H 'X-Actor-User: applicant-1' -H 'X-Actor-Role: applicant' -H 'X-Actor-Permissions: admissions.offer.accept' --data '{}')";jq -e '.status=="admitted" and .offer_status=="accepted" and .completion_percentage==100'<<<"$ACCEPTED" >/dev/null||fail "acceptance invariant failed"
attempts=30;until [[ "$(notification_count "SELECT count(*) FROM messages WHERE metadata->>'application_id'='$ID' AND status='cancelled'")" == "1" ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "accepted offer reminder was not cancelled";sleep 1;done
OTHER="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$PORT/api/v1/applications/$ID" -H 'X-Actor-Tenant: school-two' -H 'X-Actor-User: other' -H 'X-Actor-Permissions: admissions.application.read')";[[ "$OTHER" == 403 || "$OTHER" == 404 ]]||fail "cross tenant read returned $OTHER"
attempts=40;until [[ "$(curl --fail-with-body -sS "http://127.0.0.1:$CRM_PORT/api/v1/leads/$LEAD_ID" -H "X-Tenant-ID: $TENANT" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: admissions-officer' -H 'X-Actor-Permissions: crm.lead.read'|jq -r .stage)" == "offer_accepted" ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "CRM projection did not reach offer_accepted";sleep 1;done
SCORE="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$CRM_PORT/api/v1/leads/$LEAD_ID/score" -H "X-Tenant-ID: $TENANT" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: admissions-officer' -H 'X-Actor-Permissions: crm.lead.update')";jq -e '.score>=85 and .confidence=="high" and .rule_version=="growth-rules-2026-01" and any(.positive_factors[];.code=="lifecycle_progress")'<<<"$SCORE" >/dev/null||fail "explainable lead score did not reflect the accepted offer"
attempts=20;while [[ "$(COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d admissions -tAc 'SELECT count(*) FROM admissions_outbox WHERE published_at IS NULL')" != "0" ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "admissions outbox did not drain";sleep 1;done
ANALYTICS_HEADERS=(-H "X-Tenant-ID: $TENANT" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: executive' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: analytics.executive.read')
attempts=40;until EXECUTIVE="$(curl --fail-with-body -sS "http://127.0.0.1:$ANALYTICS_PORT/api/v1/analytics/executive/growth" "${ANALYTICS_HEADERS[@]}")" && jq -e --arg programme "$PROGRAMME" 'any(.funnel[]; .stage=="offers_accepted" and .count>=1) and any(.by_source[]; .key=="admissions_smoke" and .offers_accepted>=1) and any(.by_programme[]; .key==$programme and .offers_accepted==1)'<<<"$EXECUTIVE" >/dev/null;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "Growth executive projection did not reconcile the conversion";sleep 1;done
ANALYTICS_OTHER="$(curl -sS -o /dev/null -w '%{http_code}' "http://127.0.0.1:$ANALYTICS_PORT/api/v1/analytics/executive/growth" -H 'X-Tenant-ID: school-two' -H 'X-Actor-Tenant: school-two' -H 'X-Actor-User: other-executive' -H 'X-Actor-Permissions: analytics.executive.read')";[[ "$ANALYTICS_OTHER" == 403 ]]||fail "disabled tenant Growth analytics returned $ANALYTICS_OTHER"
EXECUTIVE_ANSWER="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$ANALYTICS_PORT/api/v1/analytics/executive/query" "${ANALYTICS_HEADERS[@]}" -H 'Content-Type: application/json' --data '{"question":"Which channel generated accepted offers?"}')";jq -e '.confidence=="high" and (.source_datasets|length)>=1 and (.calculation_notes|length)>=1 and (.dashboard_url|startswith("/admin/analytics"))'<<<"$EXECUTIVE_ANSWER" >/dev/null||fail "cited executive answer omitted its evidence"
printf 'Admissions conversion smoke passed: tenant=%s programme=%s intake=%s lead=%s application=%s offer=accepted crm=offer_accepted score=explainable notifications=sent+reminder-cancelled analytics=funnel+source+programme+query\n' "$TENANT" "$PROGRAMME" "$INTAKE" "$LEAD_ID" "$ID"
