#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";RUN_DIR="$(mktemp -d "${TMPDIR:-/tmp}/auraedu-actions-smoke.XXXXXX")";GO_BIN="${GO_BIN:-/opt/homebrew/bin/go}";COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-auraedu-infra}";CRM_PORT="${CRM_PORT:-18105}";ACTION_PORT="${ACTION_PORT:-18111}";TENANT="${TENANT_ID:-upshs}";PIDS=()
cleanup(){ for pid in "${PIDS[@]:-}";do pkill -TERM -P "$pid" 2>/dev/null||true;kill "$pid" 2>/dev/null||true;done;wait "${PIDS[@]:-}" 2>/dev/null||true; }
trap cleanup EXIT INT TERM
fail(){ printf 'Controlled action smoke failed: %s\n' "$1" >&2;for log in "$RUN_DIR"/*.log;do [[ -f "$log" ]]&&tail -n 100 "$log" >&2;done;exit 1; }
status(){ curl -sS -o /dev/null -w '%{http_code}' "$@"; }
ready(){ local port="$1" attempts=60;until curl --fail --silent "http://127.0.0.1:$port/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "service on $port not ready";sleep 1;done; }
command -v docker >/dev/null||fail "docker required";command -v curl >/dev/null||fail "curl required";command -v jq >/dev/null||fail "jq required";[[ -x "$GO_BIN" ]]||fail "Go missing"
cd "$ROOT_DIR";COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml up -d postgres >/dev/null
COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d postgres -v ON_ERROR_STOP=1 <<'SQL' >/dev/null
SELECT 'CREATE DATABASE crm' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='crm')\gexec
SELECT 'CREATE DATABASE assistant' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='assistant')\gexec
SQL
(cd "$ROOT_DIR/apps/crm-service"&&FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/crm?sslmode=disable" PORT="$CRM_PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/crm-service server)>"$RUN_DIR/crm.log" 2>&1&PIDS+=("$!")
ready "$CRM_PORT"
(cd "$ROOT_DIR/apps/ai-orchestrator-service"&&FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/assistant?sslmode=disable" SERVICE_CRM_URL="http://127.0.0.1:$CRM_PORT" SERVICE_KNOWLEDGE_URL="http://127.0.0.1:9" PORT="$ACTION_PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/ai-orchestrator-service server)>"$RUN_DIR/action.log" 2>&1&PIDS+=("$!")
ready "$ACTION_PORT"
NONCE="$(date +%s)-$$";OWNER_ID="$(uuidgen|tr '[:upper:]' '[:lower:]')";KEY="controlled-action-smoke-$NONCE"
LEAD="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$CRM_PORT/api/v1/public/leads" -H 'Content-Type: application/json' -H "X-Tenant-Code: $TENANT" -H "Idempotency-Key: lead-$NONCE-0000000000" --data "{\"first_name\":\"Ama\",\"last_name\":\"Controlled\",\"email\":\"ama.$NONCE@example.com\",\"phone\":null,\"institution_id\":null,\"preferred_programme_ids\":[],\"preferred_intake_id\":null,\"source\":\"controlled_action_smoke\",\"campaign_id\":null,\"message\":null,\"consent\":{\"privacy_notice_version\":\"2026-01\",\"email\":true,\"sms\":false,\"whatsapp\":false,\"voice\":false}}")";LEAD_ID="$(jq -r .lead_id<<<"$LEAD")";[[ "$LEAD_ID" != null && -n "$LEAD_ID" ]]||fail "lead capture failed"
BASE=(-H 'Content-Type: application/json' -H "X-Tenant-Id: $TENANT" -H "X-Actor-Tenant: $TENANT");PROPOSER=(-H 'X-Actor-User: ai-planner' -H 'X-Actor-Role: ai_agent' -H 'X-Actor-Permissions: ai.agent.configure');REVIEWER=(-H 'X-Actor-User: admissions-director' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: ai.agent.configure,ai.action.approve,crm.lead.assign')
DISABLED="$(status "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions" -H 'X-Tenant-Id: school-two' -H 'X-Actor-Tenant: school-two' -H 'X-Actor-User: ai-other' -H 'X-Actor-Role: ai_agent' -H 'X-Actor-Permissions: ai.agent.configure')";[[ "$DISABLED" == 403 ]]||fail "disabled tenant returned $DISABLED"
PROHIBITED="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions" "${BASE[@]}" "${PROPOSER[@]}" -H "Idempotency-Key: prohibited-$NONCE" --data "{\"action\":\"admissions.offer.issue\",\"target_id\":\"$LEAD_ID\",\"payload\":{},\"reason\":\"Attempt a prohibited final admissions action.\"}")";[[ "$PROHIBITED" == 403 ]]||fail "prohibited action returned $PROHIBITED"
PROPOSAL_BODY="{\"action\":\"crm.lead.assign\",\"target_id\":\"$LEAD_ID\",\"payload\":{\"owner_user_id\":\"$OWNER_ID\"},\"reason\":\"Assign this qualified enquiry to the admissions owner on duty.\"}"
PROPOSAL="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions" "${BASE[@]}" "${PROPOSER[@]}" -H "Idempotency-Key: $KEY" --data "$PROPOSAL_BODY")";ACTION_ID="$(jq -r .id<<<"$PROPOSAL")";jq -e '.status=="pending_approval" and .level==2 and .policy_version=="2026-07-19.v1" and (.payload_hash|length)==64'<<<"$PROPOSAL" >/dev/null||fail "proposal policy evidence missing"
REPLAY="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions" "${BASE[@]}" "${PROPOSER[@]}" -H "Idempotency-Key: $KEY" --data "$PROPOSAL_BODY")";[[ "$(jq -r .id<<<"$REPLAY")" == "$ACTION_ID" ]]||fail "idempotent proposal changed action id"
CHANGED="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions" "${BASE[@]}" "${PROPOSER[@]}" -H "Idempotency-Key: $KEY" --data "{\"action\":\"crm.lead.assign\",\"target_id\":\"$LEAD_ID\",\"payload\":{\"owner_user_id\":\"$(uuidgen|tr '[:upper:]' '[:lower:]')\"},\"reason\":\"Change the replayed owner without changing the idempotency key.\"}")";[[ "$CHANGED" == 409 ]]||fail "changed replay returned $CHANGED"
SELF="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID/approve" "${BASE[@]}" -H 'X-Actor-User: ai-planner' -H 'X-Actor-Role: ai_agent' -H 'X-Actor-Permissions: ai.action.approve,crm.lead.assign' --data '{"note":"self approval"}')";[[ "$SELF" == 403 ]]||fail "AI self approval returned $SELF"
AI_REVIEW="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID/approve" "${BASE[@]}" -H 'X-Actor-User: ai-reviewer' -H 'X-Actor-Role: ai_service_account' -H 'X-Actor-Permissions: ai.action.approve,crm.lead.assign' --data '{"note":"automatic approval"}')";[[ "$AI_REVIEW" == 403 ]]||fail "separate AI approval returned $AI_REVIEW"
NO_TOOL="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID/approve" "${BASE[@]}" -H 'X-Actor-User: reviewer-no-tool' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: ai.action.approve' --data '{"note":"lacks CRM tool permission"}')";[[ "$NO_TOOL" == 403 ]]||fail "reviewer without tool permission returned $NO_TOOL"
COMPLETED="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID/approve" "${BASE[@]}" "${REVIEWER[@]}" --data '{"note":"Verified the owner is on duty and has capacity."}')";jq -e '.status=="succeeded" and .execution_attempts==1 and .result.status_code==200'<<<"$COMPLETED" >/dev/null||fail "approved action did not succeed exactly once"
LEAD_AFTER="$(curl --fail-with-body -sS "http://127.0.0.1:$CRM_PORT/api/v1/leads/$LEAD_ID" -H "X-Tenant-Id: $TENANT" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: admissions-director' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: crm.lead.read')";jq -e --arg owner "$OWNER_ID" '.owner_user_id==$owner'<<<"$LEAD_AFTER" >/dev/null||fail "CRM lead owner was not changed"
SECOND_APPROVAL="$(status -X POST "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID/approve" "${BASE[@]}" "${REVIEWER[@]}" --data '{"note":"duplicate approval"}')";[[ "$SECOND_APPROVAL" == 409 ]]||fail "duplicate execution returned $SECOND_APPROVAL"
DETAIL="$(curl --fail-with-body -sS "http://127.0.0.1:$ACTION_PORT/api/v1/ai/actions/$ACTION_ID" "${BASE[@]}" -H 'X-Actor-User: admissions-director' -H 'X-Actor-Role: school_admin' -H 'X-Actor-Permissions: ai.agent.configure')";jq -e '.action.status=="succeeded" and .action.execution_attempts==1 and (.action.result.body|keys|sort)==["lead_id","owner_user_id"] and [.audit[].event]==["proposed","approved","execution_started","execution_succeeded"]'<<<"$DETAIL" >/dev/null||fail "immutable PII-free lifecycle evidence incomplete"
if COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d assistant -v ON_ERROR_STOP=1 -c "BEGIN; SELECT set_config('app.tenant_id','$TENANT',true); UPDATE ai_action_audit SET event='tampered' WHERE action_id='$ACTION_ID'; COMMIT;" >/dev/null 2>&1;then fail "append-only audit accepted mutation";fi
printf 'Controlled action smoke passed: tenant=%s lead=%s owner=%s action=%s policy=2026-07-19.v1 level=2 AI_approval=denied tool_permission=enforced execution=once evidence=PII-free audit=append-only\n' "$TENANT" "$LEAD_ID" "$OWNER_ID" "$ACTION_ID"
