#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";RUN_DIR="$(mktemp -d "${TMPDIR:-/tmp}/auraedu-intelligence-smoke.XXXXXX")";GO_BIN="${GO_BIN:-/opt/homebrew/bin/go}";COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-auraedu-infra}";PORT="${INTELLIGENCE_PORT:-18115}";TENANT="${TENANT_ID:-upshs}";PIDS=()
cleanup(){ for pid in "${PIDS[@]:-}";do kill "$pid" 2>/dev/null||true;done;wait "${PIDS[@]:-}" 2>/dev/null||true; }
trap cleanup EXIT INT TERM
fail(){ printf 'Market intelligence smoke failed: %s\n' "$1" >&2;for log in "$RUN_DIR"/*.log;do [[ -f "$log" ]]&&tail -n 100 "$log" >&2;done;exit 1; }
status(){ curl -sS -o /dev/null -w '%{http_code}' "$@"; }
command -v docker >/dev/null||fail "docker required";command -v curl >/dev/null||fail "curl required";command -v jq >/dev/null||fail "jq required";[[ -x "$GO_BIN" ]]||fail "Go missing"
cd "$ROOT_DIR";COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml up -d postgres nats >/dev/null
COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d postgres -v ON_ERROR_STOP=1 <<'SQL' >/dev/null
SELECT 'CREATE DATABASE intelligence' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='intelligence')\gexec
SELECT 'CREATE DATABASE notification' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='notification')\gexec
SQL
(cd "$ROOT_DIR/apps/market-intelligence-service"&&FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/intelligence?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" PORT="$PORT" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/market-intelligence-service server)>"$RUN_DIR/server.log" 2>&1&PIDS+=("$!")
attempts=60;until curl --fail --silent "http://127.0.0.1:$PORT/health" >/dev/null 2>&1;do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "service not ready";sleep 1;done
(cd "$ROOT_DIR/apps/market-intelligence-service"&&DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/intelligence?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/market-intelligence-service worker)>"$RUN_DIR/worker.log" 2>&1&PIDS+=("$!")
(cd "$ROOT_DIR/apps/notification-service"&&FEATURES_REGISTRY="$ROOT_DIR/tools/smoke/fixtures/growth-features.yaml" DATABASE_URL="postgres://auraedu:auraedu@127.0.0.1:5432/notification?sslmode=disable" NATS_URL="nats://127.0.0.1:4222" NOTIFICATION_PROVIDER=mock GOCACHE="${TMPDIR:-/tmp}/auraedu-go-cache" "$GO_BIN" run ./cmd/notification-service worker)>"$RUN_DIR/notification-worker.log" 2>&1&PIDS+=("$!")
sleep 2
H=(-H 'Content-Type: application/json' -H "X-Actor-Tenant: $TENANT");MANAGE=(-H 'X-Actor-User: researcher' -H 'X-Actor-Role: growth_analyst' -H 'X-Actor-Permissions: intelligence.read,intelligence.manage');REVIEW=(-H 'X-Actor-User: compliance' -H 'X-Actor-Role: compliance_officer' -H 'X-Actor-Permissions: intelligence.review');NONCE="$(date +%s)-$$";GROUP_ID="$(uuidgen|tr '[:upper:]' '[:lower:]')"
DISABLED="$(status "http://127.0.0.1:$PORT/api/v1/intelligence/sources?kind=reputation" -H 'X-Actor-Tenant: school-two' -H 'X-Actor-User: other' -H 'X-Actor-Permissions: intelligence.read')";[[ "$DISABLED" == 403 ]]||fail "disabled tenant returned $DISABLED"
REP_SOURCE="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources" "${H[@]}" "${MANAGE[@]}" --data "{\"kind\":\"reputation\",\"name\":\"Official review profile $NONCE\",\"canonical_url\":\"https://reviews.example.edu/aura-$NONCE\",\"collection_method\":\"manual\",\"terms_reference\":\"Manual research authority LEG-14\"}")";REP_SOURCE_ID="$(jq -r .id<<<"$REP_SOURCE")"
SELF_SOURCE="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources/$REP_SOURCE_ID/review" "${H[@]}" -H 'X-Actor-User: researcher' -H 'X-Actor-Role: growth_analyst' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"self approved"}')";[[ "$SELF_SOURCE" == 409 ]]||fail "source self review returned $SELF_SOURCE"
AI_SOURCE="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources/$REP_SOURCE_ID/review" "${H[@]}" -H 'X-Actor-User: ai-reviewer' -H 'X-Actor-Role: ai_service_account' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"AI approved"}')";[[ "$AI_SOURCE" == 403 ]]||fail "AI source approval returned $AI_SOURCE"
curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources/$REP_SOURCE_ID/review" "${H[@]}" "${REVIEW[@]}" --data '{"decision":"approved","review_note":"Manual collection terms and authority verified"}' >/dev/null
OBS="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations" "${H[@]}" "${MANAGE[@]}" --data "{\"source_id\":\"$REP_SOURCE_ID\",\"category\":\"misinformation\",\"title\":\"Incorrect application deadline\",\"evidence_excerpt\":\"A public post quoted an outdated application deadline.\",\"sentiment\":\"negative\",\"programme_id\":\"$GROUP_ID\",\"campus_id\":null,\"response_draft\":\"Please refer to the verified programme page for the current deadline.\",\"observed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}")";OBS_ID="$(jq -r .id<<<"$OBS")";jq -e '.status=="pending_review" and (.evidence_sha256|length)==64'<<<"$OBS" >/dev/null||fail "evidence fingerprint missing"
AI_OBS="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$OBS_ID/review" "${H[@]}" -H 'X-Actor-User: ai-reviewer' -H 'X-Actor-Role: service_account' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"automatic"}')";[[ "$AI_OBS" == 403 ]]||fail "AI observation approval returned $AI_OBS"
curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$OBS_ID/review" "${H[@]}" -H 'X-Actor-User: communications-lead' -H 'X-Actor-Role: communications_lead' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"Evidence checked; draft remains internal and unposted"}' >/dev/null
RESOLVED="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$OBS_ID/resolve" "${H[@]}" -H 'X-Actor-User: communications-lead' -H 'X-Actor-Role: communications_lead' -H 'X-Actor-Permissions: intelligence.manage' --data '{"resolution_note":"Official deadline guidance was clarified on the owned website"}')";jq -e '.status=="resolved" and .resolution_note!=null'<<<"$RESOLVED" >/dev/null||fail "reputation issue not resolved"
RULE="$(curl --fail-with-body -sS -X PUT "http://127.0.0.1:$PORT/api/v1/intelligence/alert-rule" "${H[@]}" "${MANAGE[@]}" --data '{"threshold":2,"window_days":14}')";jq -e '.threshold==2 and .window_days==14'<<<"$RULE" >/dev/null||fail "deterministic alert rule not updated"
OBS_TWO="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations" "${H[@]}" "${MANAGE[@]}" --data "{\"source_id\":\"$REP_SOURCE_ID\",\"category\":\"misinformation\",\"title\":\"Repeated incorrect deadline\",\"evidence_excerpt\":\"A second public record repeats the outdated application deadline.\",\"sentiment\":\"negative\",\"programme_id\":\"$GROUP_ID\",\"campus_id\":null,\"response_draft\":\"Please use the verified programme deadline.\",\"observed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}")";OBS_TWO_ID="$(jq -r .id<<<"$OBS_TWO")";curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$OBS_TWO_ID/review" "${H[@]}" -H 'X-Actor-User: communications-lead' -H 'X-Actor-Role: communications_lead' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"Second independent evidence record verified"}' >/dev/null
ALERTS="$(curl --fail-with-body -sS "http://127.0.0.1:$PORT/api/v1/intelligence/alerts?status=open" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: researcher' -H 'X-Actor-Permissions: intelligence.read')";ALERT_ID="$(jq -r --arg group "$GROUP_ID" '.data[]|select(.programme_id==$group)|.id'<<<"$ALERTS")";jq -e --arg group "$GROUP_ID" '[.data[]|select(.programme_id==$group and .observation_count==2 and .threshold==2 and (.reason|length)>10)]|length==1'<<<"$ALERTS" >/dev/null||fail "explainable recurring alert not raised"
AI_ACK="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/alerts/$ALERT_ID/acknowledge" "${H[@]}" -H 'X-Actor-User: ai-reviewer' -H 'X-Actor-Role: ai_service_account' -H 'X-Actor-Permissions: intelligence.manage' --data '{"acknowledgement_note":"automatic"}')";[[ "$AI_ACK" == 403 ]]||fail "AI alert acknowledgement returned $AI_ACK"
ACK="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/alerts/$ALERT_ID/acknowledge" "${H[@]}" -H 'X-Actor-User: communications-lead' -H 'X-Actor-Role: communications_lead' -H 'X-Actor-Permissions: intelligence.manage' --data '{"acknowledgement_note":"Communications owner assigned to correct deadline misinformation"}')";jq -e '.status=="acknowledged" and .acknowledgement_note!=null'<<<"$ACK" >/dev/null||fail "alert acknowledgement failed"
attempts=30;until [[ "$(COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d notification -tAc "SELECT count(*) FROM messages WHERE tenant_id='$TENANT' AND channel='in_app' AND status='sent' AND subject='Reputation threshold alert' AND body LIKE '2 approved misinformation observations reached the threshold of 2 within 14 days.%'")" -ge 1 ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "staff reputation alert notification was not delivered";sleep 1;done
COMP_SOURCE="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources" "${H[@]}" "${MANAGE[@]}" --data "{\"kind\":\"competitor\",\"name\":\"Official programme API $NONCE\",\"canonical_url\":\"https://competitor.example.edu/api/programmes/$NONCE\",\"collection_method\":\"official_api\",\"terms_reference\":\"Official public API terms permit programme metadata use\"}")";COMP_SOURCE_ID="$(jq -r .id<<<"$COMP_SOURCE")";curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/sources/$COMP_SOURCE_ID/review" "${H[@]}" "${REVIEW[@]}" --data '{"decision":"approved","review_note":"Official API terms and rate limits verified"}' >/dev/null
COMP_OBS="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations" "${H[@]}" "${MANAGE[@]}" --data "{\"source_id\":\"$COMP_SOURCE_ID\",\"category\":\"scholarship\",\"title\":\"New engineering scholarship\",\"evidence_excerpt\":\"The official API lists a new merit scholarship for engineering applicants.\",\"sentiment\":\"unknown\",\"programme_id\":null,\"campus_id\":null,\"response_draft\":\"\",\"observed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}")";COMP_OBS_ID="$(jq -r .id<<<"$COMP_OBS")";curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$COMP_OBS_ID/review" "${H[@]}" -H 'X-Actor-User: market-lead' -H 'X-Actor-Role: market_lead' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"Official API evidence independently verified"}' >/dev/null
OLD_DATE="$(date -u -v-10d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '10 days ago' +%Y-%m-%dT%H:%M:%SZ)";RECENT_DATE="$(date -u -v-1d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '1 day ago' +%Y-%m-%dT%H:%M:%SZ)";FROM_DATE="$(date -u -v-7d +%Y-%m-%dT%H:%M:%SZ 2>/dev/null||date -u -d '7 days ago' +%Y-%m-%dT%H:%M:%SZ)"
for VERSION in old recent;do if [[ "$VERSION" == old ]];then EVIDENCE='The official engineering fee was GHS 4,000.';OBSERVED="$OLD_DATE";else EVIDENCE='The official engineering fee is now GHS 4,500.';OBSERVED="$RECENT_DATE";fi;VERSION_OBS="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations" "${H[@]}" "${MANAGE[@]}" --data "{\"source_id\":\"$COMP_SOURCE_ID\",\"category\":\"fee\",\"title\":\"Engineering programme fee\",\"evidence_excerpt\":\"$EVIDENCE\",\"sentiment\":\"unknown\",\"programme_id\":\"$GROUP_ID\",\"campus_id\":null,\"response_draft\":\"\",\"observed_at\":\"$OBSERVED\"}")";VERSION_ID="$(jq -r .id<<<"$VERSION_OBS")";curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$VERSION_ID/review" "${H[@]}" -H 'X-Actor-User: market-lead' -H 'X-Actor-Role: market_lead' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"Official API fee evidence independently verified"}' >/dev/null;done;TO_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
SUMMARY="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/competitor-summaries" "${H[@]}" "${MANAGE[@]}" --data "{\"period_from\":\"$FROM_DATE\",\"period_to\":\"$TO_DATE\"}")";SUMMARY_ID="$(jq -r .id<<<"$SUMMARY")";jq -e --arg group "$GROUP_ID" '.status=="pending_review" and any(.items[];.programme_id==$group and .category=="fee" and .change_type=="changed" and .previous_excerpt!=null and (.latest_excerpt|length)<=280)'<<<"$SUMMARY" >/dev/null||fail "versioned competitor comparison missing"
SUMMARY_SELF="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/competitor-summaries/$SUMMARY_ID/review" "${H[@]}" -H 'X-Actor-User: researcher' -H 'X-Actor-Role: growth_analyst' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"self approved"}')";[[ "$SUMMARY_SELF" == 409 ]]||fail "competitor summary self review returned $SUMMARY_SELF"
SUMMARY_AI="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/competitor-summaries/$SUMMARY_ID/review" "${H[@]}" -H 'X-Actor-User: ai-reviewer' -H 'X-Actor-Role: ai_service_account' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"automatic"}')";[[ "$SUMMARY_AI" == 403 ]]||fail "AI summary approval returned $SUMMARY_AI"
SUMMARY_APPROVED="$(curl --fail-with-body -sS -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/competitor-summaries/$SUMMARY_ID/review" "${H[@]}" -H 'X-Actor-User: market-director' -H 'X-Actor-Role: market_director' -H 'X-Actor-Permissions: intelligence.review' --data '{"decision":"approved","review_note":"Previous and latest official evidence independently verified"}')";jq -e '.status=="approved"'<<<"$SUMMARY_APPROVED" >/dev/null||fail "competitor summary approval failed"
COMP_RESOLVE="$(status -X POST "http://127.0.0.1:$PORT/api/v1/intelligence/observations/$COMP_OBS_ID/resolve" "${H[@]}" -H 'X-Actor-User: market-lead' -H 'X-Actor-Permissions: intelligence.manage' --data '{"resolution_note":"not an issue"}')";[[ "$COMP_RESOLVE" == 409 ]]||fail "competitor observation resolved as issue: $COMP_RESOLVE"
attempts=30;while [[ "$(COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" docker compose -f deploy/docker-compose.yml exec -T postgres psql -U auraedu -d intelligence -tAc 'SELECT count(*) FROM intelligence_outbox WHERE published_at IS NULL')" != "0" ]];do attempts=$((attempts-1));[[ $attempts -gt 0 ]]||fail "transactional outbox did not drain";sleep 1;done
COUNT="$(curl --fail-with-body -sS "http://127.0.0.1:$PORT/api/v1/intelligence/observations?kind=reputation&limit=100" -H "X-Actor-Tenant: $TENANT" -H 'X-Actor-User: researcher' -H 'X-Actor-Permissions: intelligence.read'|jq --arg id "$OBS_ID" '[.data[]|select(.id==$id and .status=="resolved")]|length')";[[ "$COUNT" == 1 ]]||fail "tenant review register missing resolved observation"
printf 'Market intelligence smoke passed: tenant=%s reputation=%s status=resolved alert=%s threshold=2/14d acknowledged+notified competitor=%s summary=%s versioned+approved sources=manual+official_api AI_actions=denied outbox=drained\n' "$TENANT" "$OBS_ID" "$ALERT_ID" "$COMP_OBS_ID" "$SUMMARY_ID"
