#!/usr/bin/env node
/**
 * AuraEDU contract codegen entrypoint.
 *
 * Reads:
 *   contracts/openapi/*.yaml   -> Go server/client stubs + TypeScript types
 *   contracts/events/*.json    -> JSON-schema validators + TypeScript data types
 *   contracts/permissions/*.yaml -> shared Go/TypeScript authorization registry
 *   contracts/features/*.yaml  -> shared Go/TypeScript feature registry
 *
 * Emits into packages/shared-types/ (committed generated output).
 */
import { promises as fs } from "node:fs";
import { execFile as execFileCallback } from "node:child_process";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import openapiTS, { astToString } from "openapi-typescript";
import { compile as jsonSchemaToTS } from "json-schema-to-typescript";
import { generateGoStubs } from "./go-stubs.js";
import { generateEventValidators } from "./validators.js";

const execFile = promisify(execFileCallback);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..", "..", "..");
const CONTRACTS = path.join(ROOT, "contracts");
const OUT = path.join(ROOT, "packages", "shared-types");
const OPENAPI_OUT = path.join(OUT, "src", "generated", "openapi");
const EVENTS_OUT = path.join(OUT, "src", "generated", "events");
const GO_OUT = path.join(OUT, "gen", "go");
const AUTH_REGISTRY_GO = path.join(ROOT, "platform", "auth", "registry.gen.go");
const AUTH_REGISTRY_TS = path.join(OUT, "src", "generated", "authorization.ts");
const FEATURE_REGISTRY_GO = path.join(ROOT, "platform", "flags", "registry.gen.go");
const FEATURE_REGISTRY_TS = path.join(OUT, "src", "generated", "features.ts");

async function resolveGoFormatter(): Promise<string> {
  const candidates = [
    process.env.GOFMT_BIN,
    process.env.GOROOT ? path.join(process.env.GOROOT, "bin", "gofmt") : undefined,
    "/usr/local/go/bin/gofmt",
    "/opt/homebrew/bin/gofmt",
    "gofmt",
  ].filter((candidate): candidate is string => Boolean(candidate));
  for (const candidate of candidates) {
    if (candidate === "gofmt") return candidate;
    try {
      await fs.access(candidate);
      return candidate;
    } catch {
      // Try the next known installation location.
    }
  }
  return "gofmt";
}

async function rimraf(dir: string): Promise<void> {
  await fs.rm(dir, { recursive: true, force: true });
}

async function mkdirp(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
}

async function* walk(dir: string, ext: string): AsyncGenerator<string> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full, ext);
    } else if (entry.isFile() && entry.name.endsWith(ext)) {
      yield full;
    }
  }
}

function serviceName(file: string): string {
  return path.basename(file, path.extname(file)).replace(/\.v1$/, "");
}

async function generateOpenAPITS(file: string): Promise<void> {
  const service = serviceName(file);
  const raw = await fs.readFile(file, "utf8");
  const schema = yaml.load(raw) as any;
  const ast = await openapiTS(schema, {
    exportType: true,
    additionalProperties: false,
  });
  const types = astToString(ast);
  const outFile = path.join(OPENAPI_OUT, `${service}.v1.ts`);
  await fs.writeFile(
    outFile,
    `// Generated by @auraedu/codegen from contracts/openapi/${service}.v1.yaml\n// Do not edit by hand.\n\n${types}\n`,
    "utf8",
  );
  console.log(`[ts] ${path.relative(ROOT, outFile)}`);
}

async function generateOpenAPIGo(file: string): Promise<void> {
  const service = serviceName(file);
  const raw = await fs.readFile(file, "utf8");
  const schema = yaml.load(raw) as any;
  const outDir = path.join(GO_OUT, service);
  await mkdirp(outDir);
  const goCode = generateGoStubs(service, schema);
  const outFile = path.join(outDir, "openapi.gen.go");
  await fs.writeFile(outFile, goCode, "utf8");
  console.log(`[go] ${path.relative(ROOT, outFile)}`);
}

async function generateEvents(): Promise<void> {
  const files: string[] = [];
  for await (const file of walk(path.join(CONTRACTS, "events"), ".json")) {
    files.push(file);
  }
  files.sort();

  await mkdirp(EVENTS_OUT);

  // Data types
  let typesFile = `// Generated by @auraedu/codegen from contracts/events/*.json\n// Do not edit by hand.\n\n`;
  typesFile += `export interface CloudEventEnvelope<T = unknown> {\n`;
  typesFile += `  specversion: "1.0";\n`;
  typesFile += `  type: string;\n`;
  typesFile += `  source: string;\n`;
  typesFile += `  subject?: string;\n`;
  typesFile += `  id: string;\n`;
  typesFile += `  time: string;\n`;
  typesFile += `  tenant_id: string;\n`;
  typesFile += `  datacontenttype?: "application/json";\n`;
  typesFile += `  data: T;\n`;
  typesFile += `}\n\n`;

  const validatorJobs = [];
  for (const file of files) {
    const raw = await fs.readFile(file, "utf8");
    const schema = JSON.parse(raw);
    const eventType = schema.title ?? path.basename(file, ".v1.json");
    const pascal = eventType
      .split(".")
      .map((s: string) => s.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase()))
      .join("");

    // Emit a data-only TypeScript type from the event's data schema.
    const dataSchema = schema.properties?.data ?? { type: "object" };
    const dataType = await jsonSchemaToTS(dataSchema, `${pascal}Data`, {
      bannerComment: "",
      additionalProperties: false,
    });
    typesFile += `/** ${schema.description ?? eventType} */\n`;
    typesFile += `${dataType}\n`;
    typesFile += `export type ${pascal}Event = CloudEventEnvelope<${pascal}Data>;\n\n`;

    validatorJobs.push({ file, schema, eventType, pascal });
  }

  await fs.writeFile(path.join(EVENTS_OUT, "types.ts"), typesFile, "utf8");
  console.log(`[ts] ${path.relative(ROOT, path.join(EVENTS_OUT, "types.ts"))}`);

  // Validators
  await generateEventValidators(validatorJobs, path.join(EVENTS_OUT, "validators.ts"));
  console.log(`[ts] ${path.relative(ROOT, path.join(EVENTS_OUT, "validators.ts"))}`);
}

interface PermissionContract {
  version: number;
  permissions: Record<string, string[]>;
  roles: Record<string, { scope: string; note?: string; platforms?: string[] }>;
}

interface FeatureContract {
  version: number;
  features: Array<{
    key: string;
    plan_required: string;
    description: string;
    defaults: Record<string, string>;
  }>;
}

function featureIdentifier(key: string): string {
  return `Feature${key
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")}`;
}

async function generateFeatureRegistry(): Promise<void> {
  const source = path.join(CONTRACTS, "features", "features.yaml");
  const raw = await fs.readFile(source, "utf8");
  const contract = yaml.load(raw) as FeatureContract;
  if (!Array.isArray(contract.features) || contract.features.length === 0) {
    throw new Error("contracts/features/features.yaml must define at least one feature");
  }

  const seen = new Set<string>();
  const features = contract.features.map((feature) => {
    const key = feature.key?.trim();
    const planRequired = feature.plan_required?.trim();
    if (!key || !/^[a-z][a-z0-9_]*$/.test(key)) {
      throw new Error(`invalid feature key ${JSON.stringify(feature.key)}`);
    }
    if (!planRequired) throw new Error(`feature ${key} is missing plan_required`);
    if (seen.has(key)) throw new Error(`duplicate feature key ${key}`);
    seen.add(key);
    return {
      key,
      plan_required: planRequired,
      description: feature.description?.trim() ?? "",
    };
  });

  const identifiers = features.map((feature) => featureIdentifier(feature.key));
  if (new Set(identifiers).size !== identifiers.length) {
    throw new Error("feature keys produce duplicate generated identifiers");
  }

  const goConstants = features
    .map((feature, index) => `\t${identifiers[index]} = ${JSON.stringify(feature.key)}`)
    .join("\n");
  const goDefinitions = features
    .map(
      (feature, index) =>
        `\t{Key: ${identifiers[index]}, PlanRequired: ${JSON.stringify(feature.plan_required)}},`,
    )
    .join("\n");
  const goSet = features.map((feature, index) => `\t${identifiers[index]}: {},`).join("\n");
  const goCode = `// Code generated by @auraedu/codegen from contracts/features/features.yaml. DO NOT EDIT.

package flags

type FeatureDefinition struct {
\tKey          string
\tPlanRequired string
}

const (
${goConstants}
)

var featureDefinitions = []FeatureDefinition{
${goDefinitions}
}

var featureKeySet = map[string]struct{}{
${goSet}
}

func KnownFeatures() []FeatureDefinition {
\treturn append([]FeatureDefinition(nil), featureDefinitions...)
}

func IsKnownFeature(key string) bool {
\t_, ok := featureKeySet[key]
\treturn ok
}
`;
  await fs.writeFile(FEATURE_REGISTRY_GO, goCode, "utf8");
  await execFile(await resolveGoFormatter(), ["-w", FEATURE_REGISTRY_GO]);
  console.log(`[go] ${path.relative(ROOT, FEATURE_REGISTRY_GO)}`);

  const tsCode = `// Generated by @auraedu/codegen from contracts/features/features.yaml
// Do not edit by hand.

export const featureDefinitions = ${JSON.stringify(features, null, 2)} as const;

export const featureKeys = featureDefinitions.map((feature) => feature.key) as ReadonlyArray<
  (typeof featureDefinitions)[number]["key"]
>;

export type FeatureKey = (typeof featureDefinitions)[number]["key"];
export type FeaturePlan = (typeof featureDefinitions)[number]["plan_required"];
`;
  await fs.writeFile(FEATURE_REGISTRY_TS, tsCode, "utf8");
  console.log(`[ts] ${path.relative(ROOT, FEATURE_REGISTRY_TS)}`);
}

async function generateAuthorizationRegistry(): Promise<void> {
  const source = path.join(CONTRACTS, "permissions", "permissions.yaml");
  const raw = await fs.readFile(source, "utf8");
  const contract = yaml.load(raw) as PermissionContract;
  const permissionKeys = [...new Set(Object.values(contract.permissions).flat())].sort();
  const roles = Object.entries(contract.roles).map(([name, definition]) => ({
    name,
    scope: definition.scope,
    platforms: definition.platforms ?? [],
  }));

  const goPermissions = permissionKeys.map((key) => `\t${JSON.stringify(key)},`).join("\n");
  const goPermissionSet = permissionKeys.map((key) => `\t${JSON.stringify(key)}: {},`).join("\n");
  const goRoles = roles
    .map(
      (role) =>
        `\t{Name: ${JSON.stringify(role.name)}, Scope: ${JSON.stringify(role.scope)}, Platforms: []string{${role.platforms.map((item) => JSON.stringify(item)).join(", ")}}},`,
    )
    .join("\n");
  const goRoleSet = roles.map((role) => `\t${JSON.stringify(role.name)}: {},`).join("\n");
  const goRoleScopes = roles
    .map((role) => `\t${JSON.stringify(role.name)}: ${JSON.stringify(role.scope)},`)
    .join("\n");
  const goCode = `// Code generated by @auraedu/codegen from contracts/permissions/permissions.yaml. DO NOT EDIT.

package auth

type RoleDefinition struct {
\tName      string
\tScope     string
\tPlatforms []string
}

var permissionKeys = []string{
${goPermissions}
}

var permissionSet = map[string]struct{}{
${goPermissionSet}
}

var roleDefinitions = []RoleDefinition{
${goRoles}
}

var roleSet = map[string]struct{}{
${goRoleSet}
}

var roleScopes = map[string]string{
${goRoleScopes}
}

func KnownPermissions() []string { return append([]string(nil), permissionKeys...) }

func IsKnownPermission(permission string) bool {
\t_, ok := permissionSet[permission]
\treturn ok
}

func KnownRoles() []RoleDefinition {
\troles := make([]RoleDefinition, len(roleDefinitions))
\tfor i, role := range roleDefinitions {
\t\troles[i] = role
\t\troles[i].Platforms = append([]string(nil), role.Platforms...)
\t}
\treturn roles
}

func IsKnownRole(role string) bool {
\t_, ok := roleSet[role]
\treturn ok
}

func RoleScope(role string) (string, bool) {
\tscope, ok := roleScopes[role]
\treturn scope, ok
}
`;
  await fs.writeFile(AUTH_REGISTRY_GO, goCode, "utf8");
  await execFile(await resolveGoFormatter(), ["-w", AUTH_REGISTRY_GO]);
  console.log(`[go] ${path.relative(ROOT, AUTH_REGISTRY_GO)}`);

  const tsCode = `// Generated by @auraedu/codegen from contracts/permissions/permissions.yaml
// Do not edit by hand.

export const permissionKeys = ${JSON.stringify(permissionKeys, null, 2)} as const;

export const roleDefinitions = ${JSON.stringify(roles, null, 2)} as const;

export type PermissionKey = (typeof permissionKeys)[number];
export type RoleKey = (typeof roleDefinitions)[number]["name"];
`;
  await fs.writeFile(AUTH_REGISTRY_TS, tsCode, "utf8");
  console.log(`[ts] ${path.relative(ROOT, AUTH_REGISTRY_TS)}`);
}

async function generateIndexFiles(): Promise<void> {
  // OpenAPI index
  const openapiFiles = (await fs.readdir(OPENAPI_OUT))
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();
  const openapiIndex = openapiFiles
    .map(
      (f) =>
        `export * as ${path.basename(f, ".ts").replace(/[.-]/g, "_")} from "./${f.replace(/\.ts$/, ".js")}";`,
    )
    .join("\n");
  await fs.writeFile(path.join(OPENAPI_OUT, "index.ts"), `${openapiIndex}\n`, "utf8");

  // Events index
  await fs.writeFile(
    path.join(EVENTS_OUT, "index.ts"),
    `export * from "./types.js";\nexport * from "./validators.js";\n`,
    "utf8",
  );

  // Package index
  await fs.writeFile(
    path.join(OUT, "src", "index.ts"),
    `// Generated barrel — safe to re-export generated modules.\nexport * as OpenAPI from "./generated/openapi/index.js";\nexport * as Events from "./generated/events/index.js";\nexport * as Authorization from "./generated/authorization.js";\nexport * as Features from "./generated/features.js";\nexport * from "./runtime.js";\n`,
    "utf8",
  );
}

async function writeGoMod(): Promise<void> {
  const mod = `module github.com/stanleyHayes/auraedu/packages/shared-types/gen/go\n\ngo 1.26\n`;
  await fs.writeFile(path.join(GO_OUT, "go.mod"), mod, "utf8");
}

async function main(): Promise<void> {
  console.log("==> AuraEDU contract codegen");

  await rimraf(OPENAPI_OUT);
  await rimraf(EVENTS_OUT);
  await rimraf(GO_OUT);
  await mkdirp(OPENAPI_OUT);
  await mkdirp(EVENTS_OUT);
  await mkdirp(GO_OUT);

  const openapiFiles: string[] = [];
  for await (const file of walk(path.join(CONTRACTS, "openapi"), ".yaml")) {
    openapiFiles.push(file);
  }
  openapiFiles.sort();

  for (const file of openapiFiles) {
    await generateOpenAPITS(file);
    await generateOpenAPIGo(file);
  }

  await generateEvents();
  await generateAuthorizationRegistry();
  await generateFeatureRegistry();
  await generateIndexFiles();
  await writeGoMod();

  console.log("==> done");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
