#!/usr/bin/env node
/**
 * AuraEDU contract codegen entrypoint.
 *
 * Reads:
 *   contracts/openapi/*.yaml   -> Go server/client stubs + TypeScript types
 *   contracts/events/*.json    -> JSON-schema validators + TypeScript data types
 *
 * Emits into packages/shared-types/ (committed generated output).
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import openapiTS, { astToString } from "openapi-typescript";
import { compile as jsonSchemaToTS } from "json-schema-to-typescript";
import { generateGoStubs } from "./go-stubs.js";
import { generateEventValidators } from "./validators.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, "..", "..", "..");
const CONTRACTS = path.join(ROOT, "contracts");
const OUT = path.join(ROOT, "packages", "shared-types");
const OPENAPI_OUT = path.join(OUT, "src", "generated", "openapi");
const EVENTS_OUT = path.join(OUT, "src", "generated", "events");
const GO_OUT = path.join(OUT, "gen", "go");

async function rimraf(dir: string): Promise<void> {
  await fs.rm(dir, { recursive: true, force: true });
}

async function mkdirp(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
}

async function* walk(dir: string, ext: string): AsyncGenerator<string> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full, ext);
    } else if (entry.isFile() && entry.name.endsWith(ext)) {
      yield full;
    }
  }
}

function serviceName(file: string): string {
  return path.basename(file, path.extname(file)).replace(/\.v1$/, "");
}

async function generateOpenAPITS(file: string): Promise<void> {
  const service = serviceName(file);
  const raw = await fs.readFile(file, "utf8");
  const schema = yaml.load(raw) as any;
  const ast = await openapiTS(schema, {
    exportType: true,
    additionalProperties: false,
  });
  const types = astToString(ast);
  const outFile = path.join(OPENAPI_OUT, `${service}.v1.ts`);
  await fs.writeFile(
    outFile,
    `// Generated by @auraedu/codegen from contracts/openapi/${service}.v1.yaml\n// Do not edit by hand.\n\n${types}\n`,
    "utf8",
  );
  console.log(`[ts] ${path.relative(ROOT, outFile)}`);
}

async function generateOpenAPIGo(file: string): Promise<void> {
  const service = serviceName(file);
  const raw = await fs.readFile(file, "utf8");
  const schema = yaml.load(raw) as any;
  const outDir = path.join(GO_OUT, service);
  await mkdirp(outDir);
  const goCode = generateGoStubs(service, schema);
  const outFile = path.join(outDir, "openapi.gen.go");
  await fs.writeFile(outFile, goCode, "utf8");
  console.log(`[go] ${path.relative(ROOT, outFile)}`);
}

async function generateEvents(): Promise<void> {
  const files: string[] = [];
  for await (const file of walk(path.join(CONTRACTS, "events"), ".json")) {
    files.push(file);
  }
  files.sort();

  await mkdirp(EVENTS_OUT);

  // Data types
  let typesFile = `// Generated by @auraedu/codegen from contracts/events/*.json\n// Do not edit by hand.\n\n`;
  typesFile += `export interface CloudEventEnvelope<T = unknown> {\n`;
  typesFile += `  specversion: "1.0";\n`;
  typesFile += `  type: string;\n`;
  typesFile += `  source: string;\n`;
  typesFile += `  subject?: string;\n`;
  typesFile += `  id: string;\n`;
  typesFile += `  time: string;\n`;
  typesFile += `  tenant_id: string;\n`;
  typesFile += `  datacontenttype?: "application/json";\n`;
  typesFile += `  data: T;\n`;
  typesFile += `}\n\n`;

  const validatorJobs = [];
  for (const file of files) {
    const raw = await fs.readFile(file, "utf8");
    const schema = JSON.parse(raw);
    const eventType = schema.title ?? path.basename(file, ".v1.json");
    const pascal = eventType
      .split(".")
      .map((s: string) => s.replace(/(^|_)([a-z])/g, (_, __, c) => c.toUpperCase()))
      .join("");

    // Emit a data-only TypeScript type from the event's data schema.
    const dataSchema = schema.properties?.data ?? { type: "object" };
    const dataType = await jsonSchemaToTS(dataSchema, `${pascal}Data`, {
      bannerComment: "",
      additionalProperties: false,
    });
    typesFile += `/** ${schema.description ?? eventType} */\n`;
    typesFile += `${dataType}\n`;
    typesFile += `export type ${pascal}Event = CloudEventEnvelope<${pascal}Data>;\n\n`;

    validatorJobs.push({ file, schema, eventType, pascal });
  }

  await fs.writeFile(path.join(EVENTS_OUT, "types.ts"), typesFile, "utf8");
  console.log(`[ts] ${path.relative(ROOT, path.join(EVENTS_OUT, "types.ts"))}`);

  // Validators
  await generateEventValidators(
    validatorJobs,
    path.join(EVENTS_OUT, "validators.ts"),
  );
  console.log(`[ts] ${path.relative(ROOT, path.join(EVENTS_OUT, "validators.ts"))}`);
}

async function generateIndexFiles(): Promise<void> {
  // OpenAPI index
  const openapiFiles = (await fs.readdir(OPENAPI_OUT)).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();
  const openapiIndex = openapiFiles
    .map((f) => `export * as ${path.basename(f, ".ts").replace(/\./g, "_")} from "./${f.replace(/\.ts$/, ".js")}";`)
    .join("\n");
  await fs.writeFile(path.join(OPENAPI_OUT, "index.ts"), `${openapiIndex}\n`, "utf8");

  // Events index
  await fs.writeFile(
    path.join(EVENTS_OUT, "index.ts"),
    `export * from "./types.js";\nexport * from "./validators.js";\n`,
    "utf8",
  );

  // Package index
  await fs.writeFile(
    path.join(OUT, "src", "index.ts"),
    `// Generated barrel — safe to re-export generated modules.\nexport * as OpenAPI from "./generated/openapi/index.js";\nexport * as Events from "./generated/events/index.js";\n`,
    "utf8",
  );
}

async function writeGoMod(): Promise<void> {
  const mod = `module github.com/stanleyHayes/auraedu/packages/shared-types/gen/go\n\ngo 1.25\n`;
  await fs.writeFile(path.join(GO_OUT, "go.mod"), mod, "utf8");
}

async function main(): Promise<void> {
  console.log("==> AuraEDU contract codegen");

  await rimraf(OPENAPI_OUT);
  await rimraf(EVENTS_OUT);
  await rimraf(GO_OUT);
  await mkdirp(OPENAPI_OUT);
  await mkdirp(EVENTS_OUT);
  await mkdirp(GO_OUT);

  const openapiFiles: string[] = [];
  for await (const file of walk(path.join(CONTRACTS, "openapi"), ".yaml")) {
    openapiFiles.push(file);
  }
  openapiFiles.sort();

  for (const file of openapiFiles) {
    await generateOpenAPITS(file);
    await generateOpenAPIGo(file);
  }

  await generateEvents();
  await generateIndexFiles();
  await writeGoMod();

  console.log("==> done");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
