/**
 * Minimal OpenAPI -> Go stub generator.
 *
 * Emits a single openapi.gen.go per service containing:
 *   - Go structs for every schema in components.schemas
 *   - ServerInterface with one net/http method per operation
 *   - ClientInterface with typed method stubs
 */

const GO_HEADER = `// Code generated by @auraedu/codegen from the service OpenAPI contract. DO NOT EDIT.

package {PACKAGE}

import (
	"context"
	"net/http"
)
`;

function pascalCase(input: string): string {
  return input
    .split(/[^a-zA-Z0-9]+/)
    .map((part) => (part ? part.charAt(0).toUpperCase() + part.slice(1) : ""))
    .join("");
}

function goFieldName(name: string): string {
  return pascalCase(name);
}

function goType(schema: any, optional = false): string {
  if (!schema) return "interface{}";

  if (schema.$ref) {
    const ref = schema.$ref.split("/").pop();
    return optional ? `*${ref}` : ref;
  }

  const nullable = Array.isArray(schema.type) && schema.type.includes("null");
  const type = Array.isArray(schema.type)
    ? schema.type.find((t: string) => t !== "null")
    : schema.type;

  let base = "interface{}";
  switch (type) {
    case "string":
      base = "string";
      break;
    case "integer":
      base = "int";
      break;
    case "number":
      base = "float64";
      break;
    case "boolean":
      base = "bool";
      break;
    case "array":
      base = `[]${goType(schema.items, false)}`;
      break;
    case "object":
      base = mapObjectType(schema);
      break;
  }

  if (schema.type === "object" && schema.additionalProperties === true && !schema.properties) {
    base = "map[string]interface{}";
  }

  return nullable || optional ? `*${base}` : base;
}

function mapObjectType(schema: any): string {
  if (!schema.properties) return "map[string]interface{}";
  const fields: string[] = [];
  const required = new Set(schema.required ?? []);
  for (const [name, prop] of Object.entries(schema.properties)) {
    const isRequired = required.has(name);
    const isNullable = Array.isArray((prop as any).type) && (prop as any).type.includes("null");
    const fieldType = goType(prop, !isRequired && !isNullable);
    const jsonTag = isRequired ? `json:"${name}"` : `json:"${name},omitempty"`;
    fields.push(`\t${goFieldName(name)} ${fieldType} \`${jsonTag}\``);
  }
  return "struct {\n" + fields.join("\n") + "\n}";
}

function generateStruct(name: string, schema: any): string {
  if (schema.allOf && schema.allOf.length === 1 && schema.allOf[0].$ref) {
    const ref = schema.allOf[0].$ref.split("/").pop();
    return `// ${name} is an alias of ${ref}.\ntype ${name} = ${ref}\n`;
  }

  const required = new Set(schema.required ?? []);
  const fields: string[] = [];
  if (schema.properties) {
    for (const [propName, prop] of Object.entries(schema.properties)) {
      const isRequired = required.has(propName);
      const isNullable = Array.isArray((prop as any).type) && (prop as any).type.includes("null");
      const fieldType = goType(prop, !isRequired && !isNullable);
      const jsonTag = isRequired ? `json:"${propName}"` : `json:"${propName},omitempty"`;
      fields.push(`\t${goFieldName(propName)} ${fieldType} \`${jsonTag}\``);
    }
  }

  let out = `// ${name} generated from OpenAPI schema.\n`;
  out += `type ${name} struct {\n`;
  out += fields.join("\n");
  if (fields.length) out += "\n";
  out += "}\n";
  return out;
}

function operationId(method: string, path: string): string {
  const parts = path.split("/").filter(Boolean);
  const methodSuffix = method.toLowerCase() === "get" && path.includes("{") ? "ById" : "";
  const pathName = parts.map(pascalCase).join("");
  return pascalCase(method) + pathName + methodSuffix;
}

function generateServerInterface(paths: any): string {
  const methods: string[] = [];
  for (const [pathStr, ops] of Object.entries(paths ?? {})) {
    for (const [method, op] of Object.entries(ops as any)) {
      if (method === "parameters") continue;
      const id = (op as any).operationId ?? operationId(method, pathStr);
      methods.push(`\t${id}(w http.ResponseWriter, r *http.Request)`);
    }
  }
  return `// ServerInterface is implemented by the service HTTP adapter.\ntype ServerInterface interface {\n${methods.join("\n")}\n}\n`;
}

function generateClientInterface(paths: any): string {
  const methods: string[] = [];
  for (const [pathStr, ops] of Object.entries(paths ?? {})) {
    for (const [method, op] of Object.entries(ops as any)) {
      if (method === "parameters") continue;
      const id = (op as any).operationId ?? operationId(method, pathStr);
      methods.push(`\t${id}(ctx context.Context) (*http.Response, error)`);
    }
  }
  return `// ClientInterface is the generated consumer stub for this service.\ntype ClientInterface interface {\n${methods.join("\n")}\n}\n`;
}

export function generateGoStubs(service: string, schema: any): string {
  const pkg = service.replace(/-/g, "");
  let code = GO_HEADER.replace("{PACKAGE}", pkg);

  // Schemas
  const schemas = schema.components?.schemas ?? {};
  for (const [name, def] of Object.entries(schemas)) {
    if (name === "Error") continue; // standard error is provided by platform/httpx
    code += generateStruct(name, def) + "\n";
  }

  // Server + client interfaces
  code += generateServerInterface(schema.paths) + "\n";
  code += generateClientInterface(schema.paths) + "\n";

  return `${code.trimEnd()}\n`;
}
