/**
 * Generate Ajv-based CloudEvents validators from JSON Schema definitions.
 */
import { promises as fs } from "node:fs";

export async function generateEventValidators(
  jobs: Array<{ file: string; schema: any; eventType: string; pascal: string }>,
  outFile: string,
): Promise<void> {
  let code = `// Generated by @auraedu/codegen from contracts/events/*.json\n// Do not edit by hand.\n\n`;
  code += `import { type AnySchema, default as Ajv2020 } from "ajv/dist/2020.js";\n`;
  code += `import addFormats from "ajv-formats";\n\n`;
  code += `const ajv = new Ajv2020({ strict: false, allErrors: true });\n`;
  code += `addFormats(ajv);\n\n`;
  code += `export interface ValidationResult {\n`;
  code += `  valid: boolean;\n`;
  code += `  errors?: unknown[];\n`;
  code += `}\n\n`;

  for (const { schema, pascal } of jobs) {
    code += `const ${pascal}Schema = ${JSON.stringify(schema)} as AnySchema;\n`;
  }

  code += `\n`;

  for (const { pascal } of jobs) {
    const fnName = `validate${pascal}`;
    code += `export const ${fnName} = ajv.compile(${pascal}Schema);\n`;
    code += `export function ${fnName}Result(value: unknown): ValidationResult {\n`;
    code += `  const ok = ${fnName}(value) as boolean;\n`;
    code += `  return ok ? { valid: true } : { valid: false, errors: ${fnName}.errors ?? [] };\n`;
    code += `}\n`;
  }

  await fs.writeFile(outFile, code, "utf8");
}
