/**
 * Generate Ajv-based CloudEvents validators from JSON Schema definitions.
 */
import { promises as fs } from "node:fs";

export async function generateEventValidators(
  jobs: { file: string; schema: any; eventType: string; pascal: string }[],
  outFile: string,
): Promise<void> {
  let code = `// Generated by @auraedu/codegen from contracts/events/*.json\n// Do not edit by hand.\n\n`;
  code += `import Ajv, { type AnySchema } from "ajv";\n`;
  code += `import Ajv2020 from "ajv/dist/2020.js";\n`;
  code += `import addFormats from "ajv-formats";\n\n`;
  code += `const ajvDraft7 = new Ajv({ strict: false, allErrors: true });\n`;
  code += `const ajv2020 = new Ajv2020({ strict: false, allErrors: true });\n`;
  code += `addFormats(ajvDraft7);\n`;
  code += `addFormats(ajv2020);\n\n`;
  code += `export interface ValidationResult {\n`;
  code += `  valid: boolean;\n`;
  code += `  errors?: unknown[];\n`;
  code += `}\n\n`;

  for (const { schema, pascal } of jobs) {
    code += `const ${pascal}Schema = ${JSON.stringify(schema)} as AnySchema;\n`;
  }

  code += `\n`;

  for (const { pascal, schema } of jobs) {
    const fnName = `validate${pascal}`;
    const dialect = String(schema.$schema ?? "").includes("2020-12") ? "ajv2020" : "ajvDraft7";
    code += `export const ${fnName} = ${dialect}.compile(${pascal}Schema);\n`;
    code += `export function ${fnName}Result(value: unknown): ValidationResult {\n`;
    code += `  const ok = ${fnName}(value) as boolean;\n`;
    code += `  return ok ? { valid: true } : { valid: false, errors: ${fnName}.errors ?? [] };\n`;
    code += `}\n`;
  }

  await fs.writeFile(outFile, code, "utf8");
}
