// Code generated by @auraedu/codegen from contracts/permissions/permissions.yaml. DO NOT EDIT.

package auth

type RoleDefinition struct {
	Name      string
	Scope     string
	Platforms []string
}

var permissionKeys = []string{
	"academic.manage",
	"academic.read",
	"admissions.application.create",
	"admissions.application.read",
	"admissions.application.review",
	"admissions.application.submit",
	"admissions.application.update",
	"admissions.catalogue.manage",
	"admissions.offer.accept",
	"admissions.offer.issue",
	"ai.action.approve",
	"ai.agent.configure",
	"ai.approve_guidance",
	"ai.approve_predictions",
	"ai.approve_recommendations",
	"ai.view_guidance",
	"ai.view_predictions",
	"ai.view_recommendations",
	"analytics.executive.read",
	"analytics.view",
	"assessments.manage",
	"assessments.read",
	"assessments.record_scores",
	"attendance.mark",
	"attendance.read",
	"audit.read",
	"billing.manage",
	"billing.read",
	"campaign.approve",
	"campaign.budget.approve",
	"campaign.create",
	"campaign.publish",
	"campaign.read",
	"campaign.update",
	"cbt.author",
	"cbt.grade",
	"cbt.read",
	"cbt.take",
	"content.generate",
	"content.publish",
	"content.review",
	"crm.interaction.create",
	"crm.lead.assign",
	"crm.lead.create",
	"crm.lead.export",
	"crm.lead.read",
	"crm.lead.update",
	"features.manage",
	"feedback.review",
	"fees.manage",
	"fees.read",
	"files.delete",
	"files.read",
	"files.update",
	"files.upload",
	"intelligence.manage",
	"intelligence.read",
	"intelligence.review",
	"knowledge.approve",
	"knowledge.manage",
	"knowledge.read",
	"notifications.manage",
	"notifications.read",
	"notifications.send",
	"payments.configure",
	"payments.initiate",
	"payments.read",
	"reports.publish",
	"reports.read",
	"roles.assign",
	"staff.create",
	"staff.read",
	"staff.update",
	"students.create",
	"students.delete",
	"students.read",
	"students.update",
	"users.create",
	"users.read",
	"users.update",
	"website.manage",
	"website.read",
}

var permissionSet = map[string]struct{}{
	"academic.manage":               {},
	"academic.read":                 {},
	"admissions.application.create": {},
	"admissions.application.read":   {},
	"admissions.application.review": {},
	"admissions.application.submit": {},
	"admissions.application.update": {},
	"admissions.catalogue.manage":   {},
	"admissions.offer.accept":       {},
	"admissions.offer.issue":        {},
	"ai.action.approve":             {},
	"ai.agent.configure":            {},
	"ai.approve_guidance":           {},
	"ai.approve_predictions":        {},
	"ai.approve_recommendations":    {},
	"ai.view_guidance":              {},
	"ai.view_predictions":           {},
	"ai.view_recommendations":       {},
	"analytics.executive.read":      {},
	"analytics.view":                {},
	"assessments.manage":            {},
	"assessments.read":              {},
	"assessments.record_scores":     {},
	"attendance.mark":               {},
	"attendance.read":               {},
	"audit.read":                    {},
	"billing.manage":                {},
	"billing.read":                  {},
	"campaign.approve":              {},
	"campaign.budget.approve":       {},
	"campaign.create":               {},
	"campaign.publish":              {},
	"campaign.read":                 {},
	"campaign.update":               {},
	"cbt.author":                    {},
	"cbt.grade":                     {},
	"cbt.read":                      {},
	"cbt.take":                      {},
	"content.generate":              {},
	"content.publish":               {},
	"content.review":                {},
	"crm.interaction.create":        {},
	"crm.lead.assign":               {},
	"crm.lead.create":               {},
	"crm.lead.export":               {},
	"crm.lead.read":                 {},
	"crm.lead.update":               {},
	"features.manage":               {},
	"feedback.review":               {},
	"fees.manage":                   {},
	"fees.read":                     {},
	"files.delete":                  {},
	"files.read":                    {},
	"files.update":                  {},
	"files.upload":                  {},
	"intelligence.manage":           {},
	"intelligence.read":             {},
	"intelligence.review":           {},
	"knowledge.approve":             {},
	"knowledge.manage":              {},
	"knowledge.read":                {},
	"notifications.manage":          {},
	"notifications.read":            {},
	"notifications.send":            {},
	"payments.configure":            {},
	"payments.initiate":             {},
	"payments.read":                 {},
	"reports.publish":               {},
	"reports.read":                  {},
	"roles.assign":                  {},
	"staff.create":                  {},
	"staff.read":                    {},
	"staff.update":                  {},
	"students.create":               {},
	"students.delete":               {},
	"students.read":                 {},
	"students.update":               {},
	"users.create":                  {},
	"users.read":                    {},
	"users.update":                  {},
	"website.manage":                {},
	"website.read":                  {},
}

var roleDefinitions = []RoleDefinition{
	{Name: "platform_super_admin", Scope: "all_tenants", Platforms: []string{}},
	{Name: "school_admin", Scope: "single_tenant", Platforms: []string{}},
	{Name: "principal", Scope: "single_tenant", Platforms: []string{}},
	{Name: "academic_head", Scope: "single_tenant", Platforms: []string{}},
	{Name: "accountant", Scope: "single_tenant", Platforms: []string{}},
	{Name: "teacher", Scope: "assigned_classes_subjects", Platforms: []string{"web", "mobile"}},
	{Name: "parent", Scope: "own_children", Platforms: []string{"web", "mobile"}},
	{Name: "student", Scope: "own_records", Platforms: []string{"web", "mobile"}},
	{Name: "applicant", Scope: "own_applications", Platforms: []string{"web"}},
	{Name: "support_agent", Scope: "limited_platform_support", Platforms: []string{}},
}

var roleSet = map[string]struct{}{
	"platform_super_admin": {},
	"school_admin":         {},
	"principal":            {},
	"academic_head":        {},
	"accountant":           {},
	"teacher":              {},
	"parent":               {},
	"student":              {},
	"applicant":            {},
	"support_agent":        {},
}

var roleScopes = map[string]string{
	"platform_super_admin": "all_tenants",
	"school_admin":         "single_tenant",
	"principal":            "single_tenant",
	"academic_head":        "single_tenant",
	"accountant":           "single_tenant",
	"teacher":              "assigned_classes_subjects",
	"parent":               "own_children",
	"student":              "own_records",
	"applicant":            "own_applications",
	"support_agent":        "limited_platform_support",
}

func KnownPermissions() []string { return append([]string(nil), permissionKeys...) }

func IsKnownPermission(permission string) bool {
	_, ok := permissionSet[permission]
	return ok
}

func KnownRoles() []RoleDefinition {
	roles := make([]RoleDefinition, len(roleDefinitions))
	for i, role := range roleDefinitions {
		roles[i] = role
		roles[i].Platforms = append([]string(nil), role.Platforms...)
	}
	return roles
}

func IsKnownRole(role string) bool {
	_, ok := roleSet[role]
	return ok
}

func RoleScope(role string) (string, bool) {
	scope, ok := roleScopes[role]
	return scope, ok
}
