// Code generated by @auraedu/codegen from contracts/features/features.yaml. DO NOT EDIT.

package flags

type FeatureDefinition struct {
	Key          string
	PlanRequired string
}

const (
	FeaturePublicWebsite              = "public_website"
	FeatureAdmissions                 = "admissions"
	FeatureStudentManagement          = "student_management"
	FeatureStaffManagement            = "staff_management"
	FeatureAcademicManagement         = "academic_management"
	FeatureParentPortal               = "parent_portal"
	FeatureStudentPortal              = "student_portal"
	FeatureTeacherPortal              = "teacher_portal"
	FeatureAttendance                 = "attendance"
	FeatureAssignments                = "assignments"
	FeatureAssessments                = "assessments"
	FeatureCbtExams                   = "cbt_exams"
	FeatureReportCards                = "report_cards"
	FeatureFees                       = "fees"
	FeatureOnlinePayments             = "online_payments"
	FeatureTimetable                  = "timetable"
	FeatureLibrary                    = "library"
	FeatureHostel                     = "hostel"
	FeatureTransport                  = "transport"
	FeatureAnnouncements              = "announcements"
	FeatureNotifications              = "notifications"
	FeatureEmailNotifications         = "email_notifications"
	FeatureSmsNotifications           = "sms_notifications"
	FeatureWhatsappNotifications      = "whatsapp_notifications"
	FeaturePushNotifications          = "push_notifications"
	FeatureAnalytics                  = "analytics"
	FeatureAiRecommendations          = "ai_recommendations"
	FeatureAiPredictions              = "ai_predictions"
	FeatureCareerGuidance             = "career_guidance"
	FeatureBilling                    = "billing"
	FeatureCustomDomain               = "custom_domain"
	FeatureFileManagement             = "file_management"
	FeatureGrowthCrm                  = "growth_crm"
	FeatureGrowthCampaigns            = "growth_campaigns"
	FeatureGrowthContentAi            = "growth_content_ai"
	FeatureGrowthWebsiteChat          = "growth_website_chat"
	FeatureGrowthWhatsapp             = "growth_whatsapp"
	FeatureGrowthLeadScoring          = "growth_lead_scoring"
	FeatureGrowthApplicationAssistant = "growth_application_assistant"
	FeatureGrowthReputationMonitor    = "growth_reputation_monitor"
	FeatureGrowthCompetitorMonitor    = "growth_competitor_monitor"
	FeatureGrowthPredictiveAnalytics  = "growth_predictive_analytics"
	FeatureGrowthAutonomousActions    = "growth_autonomous_actions"
	FeatureGrowthAlumniMarketing      = "growth_alumni_marketing"
)

var featureDefinitions = []FeatureDefinition{
	{Key: FeaturePublicWebsite, PlanRequired: "starter"},
	{Key: FeatureAdmissions, PlanRequired: "growth"},
	{Key: FeatureStudentManagement, PlanRequired: "starter"},
	{Key: FeatureStaffManagement, PlanRequired: "starter"},
	{Key: FeatureAcademicManagement, PlanRequired: "core"},
	{Key: FeatureParentPortal, PlanRequired: "starter"},
	{Key: FeatureStudentPortal, PlanRequired: "growth"},
	{Key: FeatureTeacherPortal, PlanRequired: "starter"},
	{Key: FeatureAttendance, PlanRequired: "starter"},
	{Key: FeatureAssignments, PlanRequired: "growth"},
	{Key: FeatureAssessments, PlanRequired: "growth"},
	{Key: FeatureCbtExams, PlanRequired: "professional"},
	{Key: FeatureReportCards, PlanRequired: "starter"},
	{Key: FeatureFees, PlanRequired: "growth"},
	{Key: FeatureOnlinePayments, PlanRequired: "professional"},
	{Key: FeatureTimetable, PlanRequired: "growth"},
	{Key: FeatureLibrary, PlanRequired: "professional"},
	{Key: FeatureHostel, PlanRequired: "professional"},
	{Key: FeatureTransport, PlanRequired: "professional"},
	{Key: FeatureAnnouncements, PlanRequired: "starter"},
	{Key: FeatureNotifications, PlanRequired: "starter"},
	{Key: FeatureEmailNotifications, PlanRequired: "starter"},
	{Key: FeatureSmsNotifications, PlanRequired: "growth"},
	{Key: FeatureWhatsappNotifications, PlanRequired: "professional"},
	{Key: FeaturePushNotifications, PlanRequired: "starter"},
	{Key: FeatureAnalytics, PlanRequired: "professional"},
	{Key: FeatureAiRecommendations, PlanRequired: "ai_plus"},
	{Key: FeatureAiPredictions, PlanRequired: "ai_plus"},
	{Key: FeatureCareerGuidance, PlanRequired: "ai_plus"},
	{Key: FeatureBilling, PlanRequired: "core"},
	{Key: FeatureCustomDomain, PlanRequired: "professional"},
	{Key: FeatureFileManagement, PlanRequired: "core"},
	{Key: FeatureGrowthCrm, PlanRequired: "growth"},
	{Key: FeatureGrowthCampaigns, PlanRequired: "professional"},
	{Key: FeatureGrowthContentAi, PlanRequired: "ai_plus"},
	{Key: FeatureGrowthWebsiteChat, PlanRequired: "ai_plus"},
	{Key: FeatureGrowthWhatsapp, PlanRequired: "professional"},
	{Key: FeatureGrowthLeadScoring, PlanRequired: "professional"},
	{Key: FeatureGrowthApplicationAssistant, PlanRequired: "professional"},
	{Key: FeatureGrowthReputationMonitor, PlanRequired: "enterprise"},
	{Key: FeatureGrowthCompetitorMonitor, PlanRequired: "enterprise"},
	{Key: FeatureGrowthPredictiveAnalytics, PlanRequired: "ai_plus"},
	{Key: FeatureGrowthAutonomousActions, PlanRequired: "enterprise"},
	{Key: FeatureGrowthAlumniMarketing, PlanRequired: "enterprise"},
}

var featureKeySet = map[string]struct{}{
	FeaturePublicWebsite:              {},
	FeatureAdmissions:                 {},
	FeatureStudentManagement:          {},
	FeatureStaffManagement:            {},
	FeatureAcademicManagement:         {},
	FeatureParentPortal:               {},
	FeatureStudentPortal:              {},
	FeatureTeacherPortal:              {},
	FeatureAttendance:                 {},
	FeatureAssignments:                {},
	FeatureAssessments:                {},
	FeatureCbtExams:                   {},
	FeatureReportCards:                {},
	FeatureFees:                       {},
	FeatureOnlinePayments:             {},
	FeatureTimetable:                  {},
	FeatureLibrary:                    {},
	FeatureHostel:                     {},
	FeatureTransport:                  {},
	FeatureAnnouncements:              {},
	FeatureNotifications:              {},
	FeatureEmailNotifications:         {},
	FeatureSmsNotifications:           {},
	FeatureWhatsappNotifications:      {},
	FeaturePushNotifications:          {},
	FeatureAnalytics:                  {},
	FeatureAiRecommendations:          {},
	FeatureAiPredictions:              {},
	FeatureCareerGuidance:             {},
	FeatureBilling:                    {},
	FeatureCustomDomain:               {},
	FeatureFileManagement:             {},
	FeatureGrowthCrm:                  {},
	FeatureGrowthCampaigns:            {},
	FeatureGrowthContentAi:            {},
	FeatureGrowthWebsiteChat:          {},
	FeatureGrowthWhatsapp:             {},
	FeatureGrowthLeadScoring:          {},
	FeatureGrowthApplicationAssistant: {},
	FeatureGrowthReputationMonitor:    {},
	FeatureGrowthCompetitorMonitor:    {},
	FeatureGrowthPredictiveAnalytics:  {},
	FeatureGrowthAutonomousActions:    {},
	FeatureGrowthAlumniMarketing:      {},
}

func KnownFeatures() []FeatureDefinition {
	return append([]FeatureDefinition(nil), featureDefinitions...)
}

func IsKnownFeature(key string) bool {
	_, ok := featureKeySet[key]
	return ok
}
